development:
  host: localhost
  database: motomem_development
  autocreate_indexes: true


test:
  host: localhost
  database: motomem_test
  autocreate_indexes: true


# set these environment variables on your prod server
production:
  host: localhost
  database: motomem_production
